### ISSUE TITLE
[Question] Image Support

### ISSUE THREAD

**Issue by AblatedSprocket** [emacs-love/weblorg#49]
Is there support for parsing on Org link to an image file when exporting? For example, parsing the link as an <img> tag (or something) in the HTML output?

**Comment by clarete** [comment]
hi @AblatedSprocket thanks for taking the time to open this issue with your question.

Do you refer to inserting an Org-Mode link to an image file and get that link to be translated to an `<img>` tag?  If so, you currently have to link it directly to the file with a regular org-mode link

```
[[/path/the/image/file.png]]
```

If you're looking into using weblorg's routing system, unfortunately, `url_for` currently only generates `a` tags. e.g.:

```
[[url_for:static,file=image.png][an image]]
```

I think it'd be great to find a way to tell `url_for` to generate an `img` tag instead of a regular link.  Let me know if you have any suggestions. I'll see if I can come up with something too in the meantime 😄

**Comment by AblatedSprocket** [comment]
There's another issue open for this, but I think my ideal use case would be using plain old org syntaxes and weblorg would override the exporter. That sounds hard though

**Comment by AblatedSprocket** [comment]
What if we just add another definition in org-link-set-parameters:

```
(org-link-set-parameters
     "img"
     :export (lambda(path desc _backend)
               (format "<img href=\"%s\" />" (weblorg--url-for path site)))
```

**Comment by clarete** [comment]
Hi @AblatedSprocket 👋🏾  this looks pretty good to me.  What do you think about calling it `url_for_img`?
you can register it in `weblorg--route-install-template-filters` 🙇🏾 do you think you'd be interested in trying to put another lil PR for this? 😄

**Comment by AblatedSprocket** [comment]
You know, I just might

**Comment by clarete** [comment]
Just merged #53, thank you @AblatedSprocket for another contribution to weblorg 😄 
thank you for taking the time 🙇🏾

**Comment by AblatedSprocket** [comment]
Thanks for creating such a great library!

**Comment by clarete** [comment]
added docs for this the commit https://github.com/emacs-love/weblorg/commit/aed0eb8f6999c25a98029e141175d4548eca1876
