### ISSUE TITLE
org-file caching issue when publishing interactively

### ISSUE THREAD

**Issue by markokocic** [emacs-love/weblorg#51]
When evaluating `weblorg-export` in interactive mode, the content of org files is not updated after editing org file and publishing again. Looks like some caching issue.

**Comment by AblatedSprocket** [comment]
Possibly unrelated, but I've also noticed caching of other things as well. When I remove a file from the static directory and the output directory after exporting, the file continues to show up in the output directory on subsequent exports, despite no file in the source directory.

**Comment by clarete** [comment]
hi hi @markokocic, thank you for opening this issue and sorry for taking a bit to get to this.  I think you are right about the cache getting stale in interactive sessions.  I added a change to clean up the the cache before each export.  The cache is still useful with that because I added it to cache things between rendering *routes*.  Please let me know if that works if you ever get some time to try it out.

@AblatedSprocket, that case seems to be slightly different. Weblorg's static copy isn't really very smart.  It won't delete things that don't exist in the source directory anymore as you said because it wouldn't be able to know if that file was created by weblorg or not, and that could lead to data loss.  Maybe it'd be helpful to add a "--force" type of situation there or a prompt to confirm deletion to allow for both convenience and safety.


I'm going to close this ticket, but please reopen it or create a new one if this bug or the file deletion can be still improved 😄 

Thanks a bunch 🙇🏾
