### ISSUE TITLE
Wrong url for static resource in subfolder

### ISSUE THREAD

**Issue by markokocic** [emacs-love/weblorg#56]
I have the following static route defined
``` lisp
(weblorg-copy-static
 :site blog
 :output "output/{{ file }}"
 :url "/{{ file }}")
```
Inside a static folder I have some files in root, and some in subfolders.

I use `{{ url_for("static", file="res/file-1.pdf") }}`

Expected behaviour: I would get `"/res/file-1.pdf"` in generated file.

Actual behaviour: URL without folder gets generated, like this: `"/file-1.pdf"`

Files are copied to the correct location (in subfolder), it's only links that don't work.

**Comment by clarete** [comment]
hi hi @markokocic, sorry I took quite a bit to get to this one.
I just tried it out and it seems to be working for me, and I am under the assumption that this was actually an error in how the named parameters for functions were being parsed by templatel.  Since I just tried it out and it worked, I might mark this bug as closed.  If by any chance I just missed something, please reopen it and we'll take a deeper look!
